#ifndef ODRIVE_H
#define ODRIVE_H

// ── ODrive hardware configuration ─────────────────────────────────────────
// Uncomment ONE line to match currently connected ODrives.
// When you have all three connected, switch to ODRIVE_FULL.
// #define ODRIVE_FULL        // All three connected: nodes 0, 1, 2
#define ODRIVE_TEST_1_2      // Partial test: nodes 1 and 2 only
// ──────────────────────────────────────────────────────────────────────────

#include <Arduino.h>
#include "comms.h"

struct ODriveStatus; // Teensy compile hack

void pumpEvents(FlexCAN_T4_Base &can);
/*
Forward-declared empty struct to satisfy linker/compile-time requirements
in the autogenerated ODrive CAN message structures
*/
struct ODriveUserData {
  Heartbeat_msg_t last_heartbeat;
  bool received_heartbeat = false;
  Get_Encoder_Estimates_msg_t last_feedback;
  bool received_feedback = false;
  //to set CONTROL_MODE_TORQUE_CONTROL
  Set_Controller_Mode_msg_t last_controller_mode;
  bool received_last_controller_mode = false;
  //to set INPUT_MODE_PASSTHROUGH
  Set_Controller_Mode_msg_t last_input_mode;
  bool received_last_input_mode = false;
  Get_Iq_msg_t last_iq_msg;
  bool received_iq_current = false;
};


/* ODrive Instances ------------------------------------------------*/
extern ODriveCAN odrv0;
extern ODriveCAN odrv1;
extern ODriveCAN odrv2;

// List of all drives for message routing
extern ODriveCAN* odrives[3];

extern ODriveUserData odrv0_user_data;
extern ODriveUserData odrv1_user_data;
extern ODriveUserData odrv2_user_data;

/*
Per-ODrive initialization:
- registers callbacks
- waits for heartbeat
- transitions to closed-loop control
*/
bool initOdrive(ODriveCAN &odrv, ODriveUserData &data, uint8_t node_id);

/*
Pre-registers ODrive callbacks before CAN starts receiving messages.
This prevents the "missing callback" error when heartbeats arrive early.
*/
void preInitOdriveCallbacks();

/*
- Initializes Serial for debugging
- registers ODrive callbacks
- initializes CAN hardware
- waits for heartbeat from both ODrives
- transitions both ODrives into closed-loop control
*/
bool initMultiOdrives();

/*
Helper to transition an ODrive into closed-loop control.
*/
void enable_closed_loop(ODriveCAN &odrv, ODriveUserData &data, uint8_t node_id);

void enable_torque_control(ODriveCAN &odrv, ODriveUserData &data, uint8_t node_id);

void enable_velocity_control(ODriveCAN &odrv, ODriveUserData &data, uint8_t node_id);

void enable_position_control(ODriveCAN &odrv, ODriveUserData &data, uint8_t node_id);
/**
 * @brief Emergency stop function for all ODrives
 * 
 * @usage Called on emergency stop button press or fault detection
 * @note Immediately disables all motors and sets system to safe state
 */
void emergencyStop();


void printOdriveCurrent(ODriveCAN* odrv, ODriveUserData &data, uint8_t node_id);
bool printOdriveError(ODriveCAN* odrv, uint8_t node_id);

#endif // ODRIVE_H