#ifndef ODRIVE_H
#define ODRIVE_H

#include <Arduino.h>
#include "ODriveCAN.h"
#include <FlexCAN_T4.h>


/* CAN Settings ----------------------------------------------------*/
#define CAN_BAUDRATE 250000

// Node IDs for each ODrive
#define ODRV0_NODE_ID 0
#define ODRV1_NODE_ID 1

struct ODriveStatus; // Teensy compile hack

/* FlexCAN Interface -----------------------------------------------*/
extern FlexCAN_T4<CAN1, RX_SIZE_256, TX_SIZE_16> can_intf;
void pumpEvents(FlexCAN_T4_Base &can);
/*
Forward-declared empty struct to satisfy linker/compile-time requirements
in the autogenerated ODrive CAN message structures
*/
struct ODriveUserData {
  Heartbeat_msg_t last_heartbeat;
  bool received_heartbeat = false;
  Get_Encoder_Estimates_msg_t last_feedback;
  bool received_feedback = false;
  //to set CONTROL_MODE_TORQUE_CONTROL
  Set_Controller_Mode_msg_t last_controller_mode;
  bool received_last_controller_mode = false;
  //to set INPUT_MODE_PASSTHROUGH
  Set_Controller_Mode_msg_t last_input_mode;
  bool received_last_input_mode = false;
};


/* ODrive Instances ------------------------------------------------*/
extern ODriveCAN odrv0;
extern ODriveCAN odrv1;

// List of all drives for message routing
extern ODriveCAN* odrives[2];

extern ODriveUserData odrv0_user_data;
extern ODriveUserData odrv1_user_data;


/*
Routes every incoming CAN frame to each ODriveCAN instance so each can decide
whether the frame matches its configured node ID
*/
void onCanMessage(const CAN_message_t& msg);
/*
Stores incoming heartbeat message and marks drive as detected on CAN bus
*/
void onHeartbeat(Heartbeat_msg_t& msg, void* user_data);

/*
Records encoder position and velocity for the associated ODrive
*/
void onFeedback(Get_Encoder_Estimates_msg_t& msg, void* user_data);

/*
Sets up odrive CAN reqs
*/
bool setupCan();

/*
One-time system initialization:
- initializes Serial
- initializes CAN
- initializes I2C sensors
*/
bool initOdriveSystem();

/*
Per-ODrive initialization:
- registers callbacks
- waits for heartbeat
- transitions to closed-loop control
*/
bool initOdrive(ODriveCAN &odrv, ODriveUserData &data);

/*
- Initializes Serial for debugging
- registers ODrive callbacks
- initializes CAN hardware
- waits for heartbeat from both ODrives
- transitions both ODrives into closed-loop control
*/
bool initMultiOdrives();

/*
Helper to transition an ODrive into closed-loop control.
*/
void enable_closed_loop(ODriveCAN &odrv, ODriveUserData &data);

/**
 * @brief Emergency stop function for all ODrives
 * 
 * @usage Called on emergency stop button press or fault detection
 * @note Immediately disables all motors and sets system to safe state
 */
void emergencyStop();


void setOdriveTorque(ODriveCAN &odrv, ODriveUserData &data, float torque);

void stopOdrive(ODriveCAN &odrv, ODriveUserData &data);


#endif // ODRIVE_H